[application]

# App (Project) Name
name = "dioxus-simple-pdf-tools"

[web.app]

# HTML title tag content
title = "dioxus-simple-pdf-tools"
# The application will be served at domain.com/dioxus-simple-pdf-tools/, so we need to modify the base_path to the path where the application will be served
base_path = "dioxus-simple-pdf-tools"
out_dir = "docs"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
